apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: mbeng44/result-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

