apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:mbeng44/result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbeng44/result
  template:
    metadata:
      labels:
        app: mbeng44/result
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result
        name: result
        ports:
        - containerPort: 80
          name: result
