apiVersion: v1
kind: Service
metadata:
  labels:
    app: mbeng44/result
  name: result
spec:
  type: NodePort
  ports:
  - name: "result"
    port: 5000
    targetPort: 80
    nodePort: 31001
  selector:
    app: mbeng44/result
